name: Run Postman Collection
inputs:
  postman-collection:
    description: Postman Collection
    required: true
  postman-environment:
    description: Postman Collection Environment
    required: true
  report-filename:
    description: Filename of the Report
    required: true
    default: report

runs:
  using: "composite"
  steps:
    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
      shell: bash

    - name: Create Directory for Postman results
      run: mkdir -p postmanResults
      shell: bash

    - name: Test
      run: pwd && ls
      shell: bash

    - name: Run collections
      run: newman run ${{ inputs.postman-collection }} \
        -e ${{ inputs.postman-environment }} \
        -r htmlextra \
        --report-htmlextra-export postmanResults/${{ inputs.report-filename }}.html
      shell: bash

    - name: Upload Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.report-filename }}
        path: postmanResults/${{ inputs.report-filename }}.html
