name: Post Jira Comment
description: "Post comment to Jira issues containing test results and report urls"

inputs:
  project-name:
    description: "The name of the project for which the reports are being posted"
    required: true
  reports:
    description: An array of json objects reports urls objects
    required: true
  ticket:
    description: "Consists of the ticket abbreviation and key. e.g. ITU-269"
    required: true
  jira-user-email:
    description: "The email of the Jira user for publishing the deployment URL"
    required: true
  jira-user-api-token:
    description: "The api token from the Jira user used for authentication to Jira"
    required: true

runs:
  using: composite
  steps:
    - name: Build Jira API Payload
      id: build-jira-api-payload
      if: always()
      shell: bash
      run: |
        comment="${{ inputs.project-name }} API-Test-Report:"
        
        while IFS= read -r entry; do
          name=$(echo "$entry" | jq -r '.name')
          url=$(echo "$entry" | jq -r '.reportUrl')
          succeeded=$(echo "$entry" | jq -r '.succeeded')
        
          comment+=" \\\\ $name:$succeeded - $url"
        done < <(echo '${{ inputs.reports }}' | jq -c '.[]')
        
        jiraPayload=$(jq -n -c \
          --arg bodyContent "$comment" \
          '{
            body: $bodyContent,
            visibility: {
              type: "role",
              value: "Members"
            }
          }')
        
        echo $jiraPayload
        echo "jiraPayload=$jiraPayload" >> $GITHUB_OUTPUT

    - name: Publish Jira Comment
      shell: bash
      if: always()
      run: |
          curl --request POST \
               --url 'https://austrianstandards.atlassian.net/rest/api/2/issue/ITU-269/comment' \
               --user '${{ inputs.jira-user-email }}:${{ inputs.jira-user-api-token }}' \
               --header 'Accept: application/json' \
               --header 'Content-Type: application/json' \
               --data '${{ steps.build-jira-api-payload.outputs.jiraPayload }}'