name: Post Jira Comment
description: "Post comment to Jira issues containing test results and report urls"

inputs:
  reports:
    description: An array of reports urls
    required: true
  ticket:
    description: "Consists of the ticket abbreviation and key. e.g. ITU-269"
    required: true
  jira_user_email:
    description: "The email of the Jira user for publishing the deployment URL"
    required: true
  jira_user_api_token:
    description: "The api token from the Jira user used for authentication to Jira"
    required: true

runs:
  using: composite
  steps:
     - name: Print json
       if: always()
       shell: bash
       run: echo `${{ inputs.reports }}` | jq .name