name: Post Jira Comment
description: "Post comment to Jira issues containing test results and report urls"

inputs:
  reports:
    description: An array of json objects reports urls objects
    required: true
  ticket:
    description: "Consists of the ticket abbreviation and key. e.g. ITU-269"
    required: true
  jira_user_email:
    description: "The email of the Jira user for publishing the deployment URL"
    required: true
  jira_user_api_token:
    description: "The api token from the Jira user used for authentication to Jira"
    required: true

runs:
  using: composite
  steps:
    - name: Print reports
      shell: bash
      run: echo '${{ inputs.reports }}'

    - name: Print json
      shell: bash
      run: |
        echo '${{ inputs.reports }}' | while IFS= read -r entry; do
          echo "---------------------------"
          echo "Full JSON object: $entry"
        
          name=$(echo "$entry" | jq -r '.name')
          url=$(echo "$entry" | jq -r '.reportUrl')
          succeeded=$(echo "$entry" | jq -r '.succeeded')
          echo "Name: $name"
          echo "URL: $url"
        done