name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]

jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

  api-tests:
    name: Data-Driven API Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: "basic"
            test-name: "Basic Tests"
            report-filename: positive-report
          - folder: "fail"
            test-name: "Fail Tests"
            report-filename: negative-report
    outputs:
      basic-result: ${{ steps.build_postman_run_output.outputs.basic-result }}
      fail-result: ${{ steps.build_postman_run_output.outputs.fail-result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Postman Collections
        id: postman_run
        uses: ./.github/workflows/actions/postman-run-collections
        with:
          test-name: ${{ matrix.test-name }}
          collection: ./dog.collection.json
          folder: ${{matrix.folder}}
          report-filename: ${{matrix.report-filename}}

      - name: Store Postman Results as Outputs
        id: build_postman_run_output
        if: always()
        run: |
          echo '${{ matrix.folder }}-result=${{ steps.postman_run.outputs.report }}' >> $GITHUB_OUTPUT

      - name: Use Matrix Output Storage
        if: always()
        uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.folder }}
          outputs: |-
            result: ${{ steps.postman_run.outputs.report }}

  post-comment:
    needs:
      - api-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Read Matrix Outputs Storage
        if: always()
        uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: api-tests

      - name: Convert Matrix Outputs to JSON Array
        id: convert_matrix_outputs_to_json_array
        if: always()
        run: |
          result=${{ toJSON(steps.read.outputs.result) }}
          echo result=$(echo "$result" | jq '.result' | jq -c 'to_entries[] | .value' | jq -s) >> $GITHUB_OUTPUT

      - name: Post Comment on Jira
        uses: ./.github/workflows/actions/jira-commenter
        if: always()
        with:
          project-name: 'IPP'
          reports: '${{ steps.convert_matrix_outputs_to_json_array.outputs.result }}'
          ticket: 'ITU-269'
          jira-user-email: ${{secrets.JIRA_USER_EMAIL}}
          jira-user-api-token: ${{secrets.JIRA_USER_API_TOKEN}}
