name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]

jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

  api-tests:
    name: Data-Driven API Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: "basic"
            test-name: "Basic Tests"
            report-filename: positive-report
          - folder: "fail"
            test-name: "Fail Tests"
            report-filename: negative-report
    outputs:
      basic-result: ${{ steps.build_postman_run_output.outputs.basic-result }}
      fail-result: ${{ steps.build_postman_run_output.outputs.fail-result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Postman Collections
        id: postman_run
        uses: ./.github/workflows/actions/postman-run-collections
        with:
          test-name: ${{ matrix.test-name }}
          collection: ./dog.collection.json
          folder: ${{matrix.folder}}
          report-filename: ${{matrix.report-filename}}

      - name: Store Postman Results as Outputs
        id: build_postman_run_output
        if: always()
        run: |
          echo '${{ matrix.folder }}-result=${{ steps.postman_run.outputs.report }}' >> $GITHUB_OUTPUT

      - name: Use Matrix Output Storage
        if: always()
        uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.folder }}
          outputs: |-
            result: ${{ steps.postman_run.outputs.report }}

  post-comment:
    needs:
      - api-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Read Matrix Outputs Storage
        if: always()
        uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: api-tests

      - name: Print Matrix
        if: always()
        run: |
          echo "Matrix folder: ${{ matrix.folder }}"
          echo "First Attempt Results: ${{ toJSON(needs.api-tests.outputs) }}"
          echo "Action Matrix Results: ${{ steps.read.outputs.result }}"
          echo "First result: ${{ steps.read.outputs.result.result.basic }}"

      - name: Post Comment on Jira
        uses: ./.github/workflows/actions/jira-commenter
        if: always()
        with:
          reports: '${{ steps.build_report.outputs.report }}'
          jira_user_api_token: 'api-token'
          ticket: 'TEST-123'
          jira_user_email: 'username'