name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]
  workflow_dispatch:

run-name: >-
  IPP - Postman API Tests 
  ${{ github.event_name == 'repository_dispatch' && format('Pull Request ({0})', github.event.client_payload.pr_name) 
      || github.event_name == 'workflow_dispatch' && format('Start API Tests (Manual)') 
      || format('Start API Tests') }}

jobs:
  pr-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print PR Merge Event
        if: github.event_name == 'repository_dispatch'
        run: echo "PR Title ${{ github.event.client_payload.pr_name }} and ${{ github.event.name }}"


