name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]
  workflow_dispatch:

run-name: >-
  IPP - Postman API Tests 
  ${{ github.event_name == 'repository_dispatch' && format(': {0}', github.event.client_payload.pr_title) || format('not working') }}

jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print PR Merge Event
        run: echo "PR Title ${{ github.event.client_payload.pr_name }} and ${{ github.event.name }}"


