name: Postman API Tests

on:
  schedule:
    - cron: 2 * * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Newman
        run: npm install -g newman

      - name: Run collections
        run: newman run ipp.collection.json -e ipp.qa.environment.json --env-var "apiKey=${{ secrets.APIKEY }}" --env-var "cf-client=${{ secrets.CF_CLIENT }}" --env-var "cf-pw=${{ secrets.CF_PW }}"
