name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-pr-merge]

jobs:
  api-tests:
    name: IPP API Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test-run-name: "One-Time API Tests"
            folder: "One-Time Tests"
            datasource: ""
            report-filename: ipp-ot-api-report

          - test-run-name: "Data-Driven API Tests"
            folder: "Data-Driven Tests"
            datasource: ./ipp/datasource.json
            report-filename: ipp-dd-api-report
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Postman Collections
        id: execute-postman-collections
        uses: ./.github/workflows/actions/postman-run-collection
        with:
          test-run-name: ${{matrix.test-run-name}}
          collection: ./ipp/collection.json
          environment: ./ipp/qa.environment.json
          datasource: ${{matrix.datasource}}
          folder: ${{matrix.folder}}
          report-filename: ${{matrix.report-filename}}

      - name: Use Matrix Output Storage
        uses: cloudposse/github-action-matrix-outputs-write@v1
        if: always()
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.folder }}
          outputs: |-
            result: ${{ steps.execute-postman-collections.outputs.report }}

  post-comment:
    needs:
      - api-tests
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'repository_dispatch' && github.event.action == 'ipp-pr-merge' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Read Matrix Outputs Storage
        uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: api-tests

      - name: Convert Matrix Outputs to JSON Array
        id: convert-matrix-outputs-to-json_array
        run: |
          result=${{ toJSON(steps.read.outputs.result) }}
          echo result=$(echo "$result" | jq '.result' | jq -c 'to_entries[] | .value' | jq -s) >> $GITHUB_OUTPUT

      - name: Post Comment on Jira
        uses: ./.github/workflows/actions/jira-commenter
        with:
          project-name: 'IPP'
          reports: '${{ steps.convert-matrix-outputs-to-json_array.outputs.result }}'
          ticket-key: ${{ github.event.client_payload.ticket_key }}
          jira-user-email: ${{secrets.JIRA_USER_EMAIL}}
          jira-user-api-token: ${{secrets.JIRA_USER_API_TOKEN}}