name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]

jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

  api-tests:
    name: Data-Driven API Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: "basic"
            test-name: "Basic Tests"
            report-filename: positive-report
          - folder: "fail"
            test-name: "Fail Tests"
            report-filename: negative-report
    outputs:
      basic-result: ${{ steps.postman_run.outputs.basic-result }}
      fail-result: ${{ steps.postman_run.outputs.fail-result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Postman Collections
        id: postman_run
        uses: ./.github/workflows/actions/postman-run-collections
        with:
          test-name: ${{ matrix.test-name }}
          collection: ./dog.collection.json
          folder: ${{matrix.folder}}
          report-filename: ${{matrix.report-filename}}

      - name: Store Postman Results as Outputs
        if: always()
        run: |
          echo '${{ matrix.folder }}-result=${{ steps.postman_run.outputs.report }}' >> $GITHUB_OUTPUT

  post-comment:
    needs:
      - api-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Print Matrix
        if: always()
        run: |
          echo "Matrix folder: ${{ matrix.folder }}"
          echo "Basic Results: ${{ needs.api-tests.outputs }}"
          echo "Fail Results: ${{ needs.api-tests.outputs.fail-result }}"
          

      - name: Post Comment on Jira
        uses: ./.github/workflows/actions/jira-commenter
        if: always()
        with:
          reports: '${{ steps.build_report.outputs.report }}'
          jira_user_api_token: 'api-token'
          ticket: 'TEST-123'
          jira_user_email: 'username'