name: Postman API Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Postman Collections
        uses: ./.github/workflows/actions/postman-run-collections
        with:
          postman-collection: ipp.collection.json
          postman-environment: ipp.qa.environment.json
          report-filename: ipp-api-report
          api-key: "TESTSETEST"
          cf-client: "TESTCFCLIENT"
          cf-password: "TESTCFPASSWORD"

