name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]

jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Do API Tests (Fail)
        run: |
          echo "Failed API Tests"
          exit 1

  post-comment:
    needs:
      - pr-merge
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4.2.2
      - name: Post Comment on Jira
        uses: ./.github/workflows/actions/jira-commenter
        if: always()
        with:
          reports: ${{ github.event.client_payload.reports }}
          jira_user_api_token: 'api-token'
          ticket: 'TEST-123'
          jira_user_email: 'username'