name: Postman API Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ipp-merge-pr]

run-name: API Tests for ${{ github.event.client_payload.pr_name }} 


jobs:
  pr-merge:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Print PR Merge Event
        run: echo "This job runs on PR merge events. ${{ github.event.client_payload.pr_name }}"


