name: Postman API Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Newman
        run: npm install -g newman

      - name: Run collections
        run: newman run create.collection.json
